---
title: "Advanced Rgeoprofile"
author: "Michael Stevens"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Advanced Rgeoprofile}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Allocations and profile peaks

```{r, eval = FALSE}

# plot allocation
geoPlotAllocation(mcmc = m)

# plot co-allocation
geoPlotCoallocation(mcmc = m)

# produce perspective plots
# probabilities
geoPersp(surface = m$posteriorSurface, 
         aggregate_size = 3, 
         surface_type = "prob")
         
# ranked surface
geoPersp(surface = m$geoProfile, aggregate_size = 3)

# find centroids of data split by best grouping (placeholder for more thorough method)
ms <- geoModelSources(mcmc = m, data = d)
ms

# add peaks to map
# NB requires ggplot2
library(ggplot2)
mapSource <- mapGP + geom_point(aes(ms$longitude,ms$latitude), size = 6, pch = 3, col = "red")
mapSource

# # plot surface in style of 'unknown pleasures', for fun
# unknownPleasures(m$geoProfile, paper_ref = "RgeoProfile 2.1.0")

# ------------------------------------------------------------------

```

# Rasters

```{r, eval = FALSE}
#------------------------------------------------------------------
# compare to alternative ring search strategy
#------------------------------------------------------------------
# compare to geoprofile based on ring search strategy
surface_ring <- geoRing(params = p, data = d, source = s, mcmc = m)
gp_ring <- geoProfile(surface = surface_ring)
# map of ring search geoprofile
mapRing <- geoPlotMap(params = p, 
                      data = d, 
                      source = s, 
                      surface = gp_ring,
                      surfaceCols = c("red", "white"))
mapRing

# hitscores of ring search geoprofile
hs_ring <- geoReportHitscores(params = p, source = s, surface = gp_ring)
hs_ring

#------------------------------------------------------------------
# incorporate GIS data
#------------------------------------------------------------------
# read in north London shapefile as mask and adjust surface
north_london_mask <- geoShapefile()

# restrict mask to Tower Hamlets
TH_mask <- north_london_mask[which(north_london_mask$NAME == "Tower Hamlets"),]
prob_masked <- geoMask(probSurface = m$posteriorSurface, 
                       params = p, mask = TH_mask,
                       operation = "outside", scaleValue = 1e-9)
gp_masked <- geoProfile(prob_masked$prob)

# plot new surface
mapMask <- geoPlotMap(params = p, 
                      data = d, 
                      source = s, 
                      surface = gp_masked, 
                      breakPercent = seq(0,25,l = 11))
#mapMask

# hs of masked surface
hs_mask <- geoReportHitscores(params = p, source = s, surface = gp_masked)
hs_mask
# zoom
zoomLon = c(-0.1, -0.01)
zoomLat = c(51.51, 51.54)
mapZoom <- geoPlotMap(lonLimits = zoomLon, 
                      latLimits = zoomLat, 
                      params = p,
                      data = d, 
                      source = s, 
                      surface = m$geoProfile)
mapZoom

#------------------------------------------------------------------
```
