---
title: "General R resources"
author: "Michael Stevens"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{General R resources}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The last three tutorials contained a lot of information to digest. In no way was it a complete guide to using R, but it should certainly start you off in the right places. To supplement these tutorials in using R, below are a collection of resources that should help you develop the skills you have already gained and put you on the right track to learning more advanced techniques in R. 

Rob Knell, a reader in evolutionary biology at QMUL has kindly provided his book *Introductory R* to the attendees of the workshop, free of charge. [Following this link](https://drive.google.com/file/d/1fffd5eoH5sThlZHb02E9Bh_cS8tSunnE/view?usp=sharing) will take you to a hard copy of the 2nd edition. Dr Knell has also provided a [draft of a third edition](http://research.sbcs.qmul.ac.uk/r.knell/intro_R_3rd_ed/) that comes in a neat html format for easy access.  

## Immediate help in R 

We have already touched briefly on getting help whilst using Rstudio. For example, using the question mark symbol, `?`, in front of a function will bring up the documentation on said function. A double `??` should be used for package documentation. Below are a few more functions you can use in R.

```{r, eval = FALSE}
help.start()     # general help
help(plot)       # help with function plot
apropos("plot")  # list all the functions containing the string plot
example(plot)    # show an example of using the plot function 

# search for plot in the help manuals and archived mailing lists
RSiteSearch("plot")

# get vignettes on using installed packages
vignette()      # show available vingettes
```

It is inevitable that at some point in your coding career, a bug in your code will lead to an error from R. This is very common when coding and is something even the most advanced users of R will have to deal with. You may have even seen a few bugs or errors when playing around with some of the examples in these tutorials. Debugging code will require some patience and detective work. However, there are many guides out there to debugging code that can offer a hand:

* [Debugging code, from Rstats](https://rstats.wtf/debugging-r-code.html)
* [Stack overflow](https://stackoverflow.com/questions/tagged/r)
* [Data flair's guide to debugging R code](https://data-flair.training/blogs/debugging-in-r-programming/)
  

## Other tutorials

The past tutorials follow a similar structure to the [Quick-R tutorials from Datacamp](https://www.statmethods.net/r-tutorial/index.html). These contain all of the subjects we have covered and more with the option to delve into a specific topic in more detail. Some other useful guides include:

* [CRAN's introduction to R manual](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf)
* [Datamentor's "Learn R Programming"](https://www.datamentor.io/r-programming/#:~:text=R%20is%20a%20programming%20language,analyze%2C%20visualize%20and%20present%20data.)
* [R tutorial's "R introduction"](http://www.r-tutor.com/r-introduction)
* [Bill Petti's Github tutorial](https://billpetti.github.io/Crash_course_in_R/)

I also think [QMUL's statistical self help resources](https://qmplus.qmul.ac.uk/course/view.php?id=13492) will be useful to anyone wanting to learn R. These are the resources we aim at undergraduate and postgraduate students looking to learn with an emphasis to apply it in environmental science. 

## Free courses requiring an account

If you're willing to commit a lot more time to learning about R, below are a few links to online courses that break down learning R into manageable chunks. However, enrolling on these free courses requires making an account. 

* [Code academy](https://www.codecademy.com/learn/learn-r)
* [Datacamp](https://www.datacamp.com/courses/free-introduction-to-r)

In addition to tutorials [here is a blog post](https://www.datasciencecentral.com/profiles/blogs/10-great-books-about-r-1) from TechTarget with a list of useful books for beginners using R. This page also provides a link to a rather exhaustive list [books related to R](https://www.r-project.org/doc/bib/R-books.html) from R project.
