---
title: "Geographic profiling background"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: references.bib
vignette: >
  %\VignetteIndexEntry{Geographic profiling background}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

RgeoProfile is an R package for carrying out geographic profiling - a technique derived from criminology that uses the spatial locations of linked crimes to infer the home location (or locations) from which the criminal is operating (@Rossmo2000). More recently, this method has been applied to problems in ecology (@Verity2014, @Faulkner2016, @Faulkner2017) and infectious disease (@LeComber2011), where "crimes" are now equivalent to animal observations or sites of infection, and "home locations" may be roosts or persistent sources of disease. Finding these sources is often a key priority - for example in malaria this may provide a more efficient method of carrying out targeted larval source management (@LeComber2011, @Verity2014).

```{r, message = FALSE, echo = FALSE}
library(RgeoProfile)
library(raster)
library(leaflet)
# read params and mcmc objects
param_dir <- system.file("extdata/params_object.rds", package = "RgeoProfile", mustWork = TRUE)
p <- readRDS(param_dir)

mcmc_dir <- system.file("extdata/mcmc_object.rds", package = "RgeoProfile", mustWork = TRUE)
m <- readRDS(mcmc_dir)

# load the data 
data(LondonExample_crimes)
data(LondonExample_sources)

# assign data
d <- LondonExample_crimes
s <- LondonExample_sources

# remake map
my_map <- geoPlotLeaflet(surface = m$geoProfile,
                         params = p,
                         data = d, 
                         source = s, 
                         surfaceCols = rev(viridis::plasma(10)),
                         opacity = 0.7,
                         threshold = 0.1,
                         crimeCex = 3,
                         sourceCex = 5,
                         sourceCol = "black",
                         gpLegend = TRUE)   

# read in north London shapefile as mask and adjust surface
north_london_mask <- geoShapefile()

# restrict mask to Tower Hamlets
TH_mask <- north_london_mask[which(north_london_mask$NAME == "Westminster"), ]
prob_masked <- geoMask(probSurface = m$posteriorSurface, 
                       params = p, mask = TH_mask,
                       operation = "outside", scaleValue = 1e-20)
gp_masked <- geoProfile(prob_masked$prob)

# plot new surface
mapMask <- geoPlotLeaflet(surface = gp_masked,
                          params = p,
                          data = d, 
                          source = s, 
                          surfaceCols = rev(viridis::plasma(10)),
                          opacity = 0.7,
                          threshold = 1,
                          crimeCex = 4,
                          sourceCex = 5,
                          sourceCol = "black",
                          gpLegend = TRUE)
mapMask
```                         

The RgeoProfile package uses the Dirichlet Process Mixture (DPM) modelling framework of @Verity2014, which was designed to place geographic profiling in a Bayesian framework and to deal with the issue of multiple sources. In simple terms, the DPM model assumes a large (strictly infinite) number of *potential* source locations, although some of these sources are assumed to be more "active" than others. The RgeoProfile algorithm then attempts to infer the number of active sources (i.e. the number of sources that gave rise to the observed data), along with the spatial locations of these sources. It does this using Markov chain Monte Carlo (MCMC) - a statistical technique that provides estimates of unknown parameters by iteratively updating our guess.

RgeoProfile is written in R, and links to C++ through the Rcpp package. The required data is nothing more than the longitude/latitude of observed "crimes". The user is also required to define a series of parameters, for example defining prior beliefs about the average distance of a crime from a source. After running the main MCMC algorithm, a large number of plotting functions are available for exploring the output and, for evaluating the efficiency of the search strategy.

## References
